version: '3.9'

services:
  web:
    build:
      context: ./board-front
      dockerfile: ../docker/Dockerfile.front.prod
      args:
        - VITE_SERVER_URL=http://localhost:8080
    restart: always
    ports:
      - "80:80"
      
  app:
    build:
      context: ./board-back
      dockerfile: ../docker/Dockerfile.back
    restart: always
    ports:
      - "8080:8080"

    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/docker-lesson?schema=public
    depends_on:
          db:
            condition: service_healthy

  db:
    image: postgres:17.2-alpine3.20
    container_name: docker-lesson-db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: docker-lesson
    healthcheck: # ヘルスチェックを追加
      test: ["CMD-SHELL", "pg_isready -U admin -d docker-lesson"]
      interval: 5s
      timeout: 5s
      retries: 5