FROM node:23-alpine3.19 AS builder

WORKDIR /app
COPY ./ /app/

ARG VITE_SERVER_URL


RUN npm install && npm run build

FROM nginx:1.27.2-alpine AS production

COPY --from=builder /app/dist /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]